#!/bin/csh 
osra unige_105829_attachment01.pdf -l /Volumes/san256/users_for_mac_system_macPro/jeannerat/mygit/osra/osra-2.1.0-1/dict/spelling.txt -a /Volumes/san256/users_for_mac_system_macPro/jeannerat/mygit/osra/osra-2.1.0-1/dict/superatom.txt -f sdf -w  test.sdf --embedded-format inchi -b -c -d -g -p -o imag -e
